### PR TITLE
Push to the thread store when message expiration is set

### PR DESCRIPTION
**Pull request by nickcatal**
signald currently sends the message expiration to the server, but does not save that expiration locally.

This changes that

### CODE REVIEW

**Comment by thefinn93** [comment]
Oddly, I thought I fixed this just a few weeks ago. Maybe it was a similar one. Annyway, while investigating this, I synced the github remote (which apparently isn't getting auto-sync'd... that's fun), and now your PR has conflicts, sorry :(

If you update your remote I'm happy to merge it.

**Comment by nickcatal** [comment]
@thefinn93 it looks like you somewhat did (which explains why your debs are acting different than your github code.)

In your update you set it so that it would update the threadStore, but didn't account for the situation where you're setting an expiration before a threadStore exists for that contact.

I updated the code to reflect that situation.

**Comment by thefinn93** [comment]
Yeah, GitHub is not the primary repo, it's just a mirror, and there was an issue with the mirroring.

**Comment by thefinn93** [comment]
Thanks for fixing that!

**Comment by nickcatal** [comment]
What's the ETA on this being in the main deb repository (or has that already happened)?

I had all my tooling built around deploying the deb and have have had to jerry-rig this branch into my project once I ran into this problem. So once there is a deb up I can go back to my cleaner deb-based workflow.

**Comment by thefinn93** [comment]
I just synced the new commits to the main repo, the CI pipeline is running [here](https://git.callpipe.com/finn/signald/commit/01633422533a2935d70bf088192082c4626ef5a9/pipelines?ref=master), when that's done the repo should be updated.

**Comment by nickcatal** [comment]
Also, thanks for merging in and maintaining things! This is an awesome project and very well laid out. It took surprisingly little work to figure out exactly how things were working and where the problem might be.

**Comment by thefinn93** [comment]
Absolutely, thanks for submitting a clean, easy-to-merge PR!

**Pull request merged**
